# Generated by Django 2.2 on 2020-11-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.TextField()),
                ('problem', models.TextField()),
                ('answer', models.CharField(max_length=100, null=True)),
                ('similar1', models.CharField(max_length=100, null=True)),
                ('similar2', models.CharField(max_length=100, null=True)),
                ('similar3', models.CharField(max_length=100, null=True)),
                ('similar4', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20)),
                ('video_title', models.CharField(max_length=80)),
                ('video_description', models.TextField()),
                ('video_img', models.TextField()),
                ('video_max_img', models.IntegerField()),
            ],
        ),
    ]
