# Generated by Django 3.1.2 on 2020-11-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionanswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.TextField()),
                ('problem', models.TextField()),
                ('answer', models.CharField(max_length=100, null=True)),
                ('similar1', models.CharField(max_length=100, null=True)),
                ('similar2', models.CharField(max_length=100, null=True)),
                ('similar3', models.CharField(max_length=100, null=True)),
                ('similar4', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
