# Generated by Django 3.1.2 on 2020-11-04 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questionanswer',
            new_name='Problem',
        ),
    ]
